### ISSUE TITLE
Create "feedback" issue template

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/pointers#1]
configure the repository to use multiple issue templates

**Comment by vantuyls** [comment]
create /issue_template directory

**Comment by vantuyls** [comment]
created /feedback.md and /submission.md for templates. 

i committed these directly because i'm a bad person.

**Comment by vantuyls** [comment]
@tobyhodges multiple templates should be properly configured. please take a look and let me know if you have any adjustments you'd like to make/see.

**Comment by tobyhodges** [comment]
Thanks @vantuyls, looks good. I've made a slight modification to set more descriptive titles for the two templates.
