### ISSUE TITLE
create Pages site

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/pointers#3]
potential structure:

- index.html
- about.html
  - brief history of project
  - organisations involved
  - why this project should exist
- submission-guide.html
- datasets.html

probably more that we haven't thought of yet

**Comment by vantuyls** [comment]
site created and living at https://carpentries.github.io/pointers/

i cant sort out how to get images/logos to show up so we'll have to deal with that later

**Comment by vantuyls** [comment]
closing this in favor of more specific issues related to the site
