### ISSUE TITLE
Diagram near top of submission page is absent

### ISSUE THREAD

**Issue by vantuyls** [carpentries/pointers#7]
The diagram on the Submission Guidelines page does not appear - i believe this may be related to issue #6 ?

**Comment by tobyhodges** [comment]
The diagram needs to be moved or duplicated for the Just The Docs site to see it. I can take care of this some time soon, when I have time to play around with the configuration and organisation of the site a bit.

**Comment by tobyhodges** [comment]
closed with [c2be47c](https://github.com/carpentries/pointers/commit/c2be47cf9d7156ae5ad607090cb1f9da916b2c36)
